version: '3.8'

services:
  leader:
    build: .
    container_name: logstream-leader
    hostname: leader
    environment:
      - NODE_ADDRESS=172.25.0.10:8001
      - IS_LEADER=true
      - MULTICAST_GROUP=239.0.0.1:9999
      - BROADCAST_PORT=8888
    networks:
      logstream-net:
        ipv4_address: 172.25.0.10
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true

  broker1:
    build: .
    container_name: logstream-broker1
    hostname: broker1
    environment:
      - NODE_ADDRESS=172.25.0.20:8002
      - IS_LEADER=false
      - MULTICAST_GROUP=239.0.0.1:9999
      - BROADCAST_PORT=8888
    networks:
      logstream-net:
        ipv4_address: 172.25.0.20
    cap_add:
      - NET_ADMIN
    depends_on:
      - leader
    stdin_open: true
    tty: true

  broker2:
    build: .
    container_name: logstream-broker2
    hostname: broker2
    environment:
      - NODE_ADDRESS=172.25.0.30:8003
      - IS_LEADER=false
      - MULTICAST_GROUP=239.0.0.1:9999
      - BROADCAST_PORT=8888
    networks:
      logstream-net:
        ipv4_address: 172.25.0.30
    cap_add:
      - NET_ADMIN
    depends_on:
      - leader
    stdin_open: true
    tty: true

networks:
  logstream-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24