services:
  node-a:
    build: ../../..
    environment:
      - NODE_ADDRESS=172.29.0.10:8001
      - MULTICAST_GROUP=239.0.0.1:9999
      - BROADCAST_PORT=8888
    networks:
      logstream-net:
        ipv4_address: 172.29.0.10
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true
    labels:
      - "logstream.test=election"
    command: sh -c "sleep 2 && /root/logstream"

  node-b:
    build: ../../..
    environment:
      - NODE_ADDRESS=172.29.0.20:8002
      - MULTICAST_GROUP=239.0.0.1:9999
      - BROADCAST_PORT=8888
    networks:
      logstream-net:
        ipv4_address: 172.29.0.20
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true
    depends_on:
      - node-a
    labels:
      - "logstream.test=election"
    command: sh -c "sleep 5 && /root/logstream"

  node-c:
    build: ../../..
    environment:
      - NODE_ADDRESS=172.29.0.30:8003
      - MULTICAST_GROUP=239.0.0.1:9999
      - BROADCAST_PORT=8888
    networks:
      logstream-net:
        ipv4_address: 172.29.0.30
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true
    depends_on:
      - node-b
    labels:
      - "logstream.test=election"
    command: sh -c "sleep 8 && /root/logstream"

networks:
  logstream-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
