services:
  leader:
    build: ../../..
    environment:
      - NODE_ADDRESS=172.25.0.10:8001
      - MULTICAST_GROUP=239.0.0.1:9999
      - BROADCAST_PORT=8888
    networks:
      logstream-net:
        ipv4_address: 172.25.0.10
    cap_add:
      - NET_ADMIN
    labels:
      - "logstream.test=single"

networks:
  logstream-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
